import = ["/Users/chris.dunphy/.config/alacritty/catppuccin/catppuccin-macchiato.toml"]

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 16

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "SemiBold"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[[mouse.bindings]]
action = "Paste"
mouse = "Right"

[[mouse.bindings]]
action = "Copy"
mouse = "Left"

[selection]
save_to_clipboard = true

[window]
decorations = "Buttonless"

[window.padding]
x = 3
y = 3
