[[language]]
name = "python"
indent = { tab-width = 4, unit = " " }
language-server = { command = "pyright-langserver", args = ["--stdio"] }
formatter = { command = "black", args=["-"] }
auto-format = true
config = {}