#!/bin/bash
code --install-extension bmalehorn.vscode-fish
code --install-extension bungcip.better-toml
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension donjayamanne.githistory
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.github-vscode-theme
code --install-extension golang.go
code --install-extension gxiao.cookiecutter
code --install-extension hashicorp.terraform
code --install-extension ivory-lab.jenkinsfile-support
code --install-extension monokai.theme-monokai-pro-vscode
code --install-extension ms-azuretools.vscode-azurefunctions
code --install-extension ms-azuretools.vscode-azureresourcegroups
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.azure-account
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension samuelcolvin.jinjahtml
code --install-extension streetsidesoftware.code-spell-checker