import = ["/Users/chris.dunphy/.config/alacritty/catppuccin/catppuccin-frappe.toml"]

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 19

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[[mouse.bindings]]
action = "Paste"
mouse = "Right"

[[mouse.bindings]]
action = "Copy"
mouse = "Left"

[selection]
save_to_clipboard = true

[window]
decorations = "none"

[window.padding]
x = 3
y = 3
